debug: false

spring:
  application: kblog
  datasource:
    mysql:
      jdbc-url: jdbc:mysql://localhost:3306/kblog?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: ENC(oAEZZ/WKW6myApNG0xkM+O7YHpi+ycWQZfZU9AowyZLNaAjn2C+VNtz0pmci9v2e)
      password: ENC(1q2KdGxpLEug/ZRUX2ar5omb7HvSzjYCW5xrAO8SUkA+dU2d9UT4N7sURPpGWiBz)
      driver-class-name: com.mysql.cj.jdbc.Driver
    h2:
      username: ENC(oAEZZ/WKW6myApNG0xkM+O7YHpi+ycWQZfZU9AowyZLNaAjn2C+VNtz0pmci9v2e)
      password: ENC(1q2KdGxpLEug/ZRUX2ar5omb7HvSzjYCW5xrAO8SUkA+dU2d9UT4N7sURPpGWiBz)
      driver-class-name: org.h2.Driver
  jpa:
    open-in-view: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
#私钥
#本配置启动前应删除 通过参数传入私钥
#如：java -jar -Djasypt.encryptor.password=私钥  projectName.war
jasypt:
  encryptor:
    password: jasypt
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG